### ISSUE TITLE
HA Startup error: Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by viktak** [nielstron/ha_syncthru#2]
I am getting this error every time my HA restarts:

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/syncthru/config_flow.py:49
Integration: syncthru
First occurred: 7:11:06 AM (1 occurrences)
Last logged: 7:11:06 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 151, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 177, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 256, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/syncthru/config_flow.py", line 48, in async_step_ssdp
    for existing_entry in (
  File "/config/custom_components/syncthru/config_flow.py", line 49, in <genexpr>
    x for x in self._async_current_entries() if x.data[CONF_URL] == self.url
KeyError: 'url'

```
The printer is on.

Let me know if I can help troubleshooting this issue.

**Comment by viktak** [comment]
Hi @nielstron ,

I'm not sure what the current status on this is, so I thought I'd drop a line to say, I till have a similar behavior on the latest Ha build:
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/syncthru/config_flow.py:38
Integration: Samsung SyncThru Printer
First occurred: 1:11:06 PM (1 occurrences)
Last logged: 1:11:06 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
    await gather_with_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency
    return await gather(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task
    return await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 205, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 232, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/syncthru/config_flow.py", line 38, in async_step_ssdp
    await self.async_set_unique_id(discovery_info[ssdp.ATTR_UPNP_UDN])
TypeError: 'SsdpServiceInfo' object is not subscriptable

```

Using HA 2022.6.2

**Comment by nielstron** [comment]
I have rebased this component on the official distributions version. Could you please upgrade the component and try and see if the error persists there?

**Comment by viktak** [comment]
This is still happening on the latest:
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/syncthru/config_flow.py:38
Integration: syncthru
First occurred: 8:42:01 AM (1 occurrences)
Last logged: 8:42:01 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
    await gather_with_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency
    return await gather(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task
    return await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 222, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 249, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/syncthru/config_flow.py", line 38, in async_step_ssdp
    await self.async_set_unique_id(discovery_info[ssdp.ATTR_UPNP_UDN])
TypeError: 'SsdpServiceInfo' object is not subscriptable
```

**Comment by nielstron** [comment]
Did you try the beta release https://github.com/nielstron/ha_syncthru/releases/tag/rc1-0.2.0?

**Comment by viktak** [comment]
Sorry about the delay...

Just updated to the latest one and the error is gone, and the state is reported correctly.

thanks for this integration!!!
